name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
    paths:
      - 'api/Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build ./api/ -t anhnguyenhcmus/bowtie2:2.5.4
      - name: push image to docker hub
        run: |
          docker login -u anhnguyenhcmus -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push anhnguyenhcmus/bowtie2:2.5.4
